REM  Created by Ajay Bramhe - Kindly use it with small customization

path=%path%;W:\wamp\bin\mysql\mysql5.5.16\bin
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/ACCOUNTS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/actionmaster.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/actionplan.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/actions.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/ADDBACK.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/ADDLREQ.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/ADDRESS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/ADJUSTMENT.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/advacelicense.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/ADVCON.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/advlicensingbillofentry.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/advlicensingexportobligation.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/advlicensingimportobligation.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/advlicensingproductdetail.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/advlicensingproductmaster.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/advlicensingrevalidation.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/aepcexchangerate.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/AIRLINE.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/allocation.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/ANNX.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/ANNX01.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/approvalmonths.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/approvals.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/approvalsdef.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/approvalsfixed.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/APR_MAR.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/APR_MAR_.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/aqls.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/ARREARS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/ARTICLEOPERATIONS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/ARTICLES.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/ASSETUTILISATION.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/attachments.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/balance.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/bankexchangerate.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/bankrealization.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/bankrelzdtl.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/bankrelzpcl.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/BANKS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/bathmatspecsheet.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/bathmatspecsheet_d.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/bgemddetail.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/bgemdmaster.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/billentry.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/BILLOFEXC.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/BILLREC.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/BK.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/BOCHECK.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/BOCOLOR.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/BOCONS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/BOdtl.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/BOJOBORDER.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/BOMST.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/books.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/BOSIZE.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/BOSTYLEDETAIL.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/BOUNITS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/BRC.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/BUDGETS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/BUNDLES.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/BUYERBANKS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/BUYERDEPTTS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/buyerdetails.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/BUYERORDERSDETAIL.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/BUYERORDERSMASTER.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/buyertabs.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/CAPACITY.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/CARESYMBOLS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/CARTONLIST.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/catalogue.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/CATALOGUECOLORS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/CATALOGUEFABRICS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/CATALOGUEPRINTS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/CATALOGUESIZES.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/categories.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/CERT.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/CESSPAID.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/CHALLANS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/CHECKBOOKS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/COGROUPS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/commentshindi.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/companies.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/composition.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/consfabcol.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/consfbrcol.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/consfnscol.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/consgraph.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/ConsistingArticles.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/ConsistingArticlesizes.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/CONSOLI.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/consolicolumns.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/consolidate.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/consolifbrcolumns.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/consolisubcolumns.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/CONSOLISUMM.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/CONSOLISUPP.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/consolisuppcolumns.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/CONSTORES.sql
rem mysql -u siddhi -pqaz@123 gems < ../gem2mysql/control.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/COSTDTLS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/COSTING.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/costingcolours.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/costingcomments.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/costingincentives.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/costingitems.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/costingoverheads.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/costingprocesses.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/costingquotes.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/costingremarks.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/costingsizes.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/COSTSHEET.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/countries.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/COURIER.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/criticalpath.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/CSTK.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/CURRENCIES.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/customsexchagerate.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/cutoffrates.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/dailywages.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/DAYBOOKS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/DBKSCHEDULE.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/DEFAULTS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/DELIVERY.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/departments.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/designations.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/destinations.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/DKCONTRL.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/DOWNTIME.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/eefcutilization.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/efficiencyparms.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/EMP.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/EMPLOYEES.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/endorsement.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/ENQUIRY.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/errorlog.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/exciseduty.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/EXECUTIVESDEALING.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/EXPREG.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/FABCANC.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/FABDEV.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/FABINSP.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/FABRICS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/FabricWidths.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/FAIRS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/fbrstat.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/fcfsapplication.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/FINAL.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/finalaccounts.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/FOLLOWUP.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/foreigndocbill.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/formatfiles.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/FORMATS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/FORMOLD.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/FOXUSER.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/garmenttypes.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/GATEDETAILS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/gatemaster.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/GENPOS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/GRPBODTL.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/GSP.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/helptable.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/HOOKSPECSHEET.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/hookspecsheet_d.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/HSCODES.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/ICTRX.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/ictrxx.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/increments.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/inspectfbr.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/inspection.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/INSPSUMM.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/INSUMM.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/INVD.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/INVDT01.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/INVDTL.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/INVM.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/INVMST.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/invoiceaddordeduct.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/invoicedetail.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/INVOICEDTL.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/invoicemaster.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/INWARDMASTER.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/isoformats.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/itemcategories.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/ITEMCATEGORIESaddl.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/ITEMCATGSIZES.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/itemdefined.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/ITEMS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/ITEMS1.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/itemsloc.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/itemvalidation.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/JOBORDER.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/JOBTYPE.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/jobworkchallans.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/JOBWORKPROCESSES.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/LAPSE.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/lcamendmentdetail.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/LCAMENDMENTMASTER.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/lcopeningdetail.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/lcopeningmaster.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/LCTRANSFERDETAIL.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/LCTRANSFERMASTER.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/leavecredits.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/LEDGERS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/lettertobank.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/lineallocation.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/lineallocationchart.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/LINELAYOUT.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/lines.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/lotinward.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/lutmaster.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/MACHINECATEGORIES.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/MACHINES.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/maintenance.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/MAP.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/MAPTEMP.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/MARGIN.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/materialinhousestatus.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/MATERIALS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/MATRCPT.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/MDLS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/merchbudget.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/messaging.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/miscissue.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/MISCSUMM.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/MNTH.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/MODULES.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/MONTH.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/MONTHLYDATA.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/monthlyovertime.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/MONTHS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/nrcertification.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/NUMBERS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/OLDCONT.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/OLDFORMS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/OPERATION.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/operations.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/OPERNS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/ordercycle.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/orderdetails.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/orderdtls.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/orderdtlsaddl.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/ORDERDTLSFORMNAMES.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/ORDERDTLSFORMS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/ORDERMASTER.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/ORDSUMM.sql
rem mysql -u siddhi -pqaz@123 gems < ../gem2mysql/ori-tcert.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/OUTSUMM.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/OUTWARDMASTER.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/OVERHEADS.sql
rem mysql -u siddhi -pqaz@123 gems < ../gem2mysql/PACKINGLIST.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/packingmat.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/packingstructure.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/packspecsheet.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/packspecsheet_d.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/parties.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/partyopbal.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/partyproducts.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/PAYMENTTERMS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/payrollregulations.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/pclmaster.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/PDPOCONS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/PDTOTAL.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/PERFORMANCEEVAL.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/performanceindicators.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/PHOFRHG.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/pieceratewages.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/PINV.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/PINVDT.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/PL.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/PLBALANCE.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/PLISTDTL.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/PLISTSUP.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/plistsupdtl.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/POPI.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/PORTS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/postingtypes.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/PREFACE.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/PREFIX.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/processcompletionstatus.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/PROCESSINWARD.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/PROCESSORDERDETAIL.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/PROCESSOUTWARD.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/procurementinward.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/procurementorderdetail.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/procurementoutward.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/prodspecsheet.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/prodspecsheet_d.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/PRODSUMM.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/PRODUCED.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/PRODUCTION.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/PRODUCTIONINWARD.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/PRODUCTIONORDERDETAIL.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/PRODUCTIONOUTWARD.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/proformainvoicedetail.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/proformainvoicemaster.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/PTD.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/PURCHASE.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/QCLGR.sql
rem mysql -u siddhi -pqaz@123 gems < ../gem2mysql/QRYARRAY).sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/QRYTABLE.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/QUARTER.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/quotaallotment.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/quotasystems.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/RAJ.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/REASONS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/registers.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/REGSBILLSDTLS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/REGSDETAIL.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/regsmaster.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/regulatorydetails.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/releaseremarks.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/REPORTS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/reportscope.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/REQPROC.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/revalidation.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/rubberbackedspecsheet.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/rubberbackedspecsheet_d.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/samplecosts.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/samplefollowup.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/SAMPLES.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/SAMPLESUPPLIERS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/samplingbudget.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/SAMPLINGCONVERSIONRATES.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/samplingdetail.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/samplingreg.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/samplingwip.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/scheduleoffinalaccounts.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/seasoncolours.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/setCopies.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/SETPRINTING.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/SHIPINST.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/SHIPMENTMASTER.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/SHIPMENTS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/shipmentschedule.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/sizes.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/SKILLEDWORKERS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/SKILLSETS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/SM0PCOBS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/specdetails.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/specmaster.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/specsheet.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/specsheet_d.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/STITEMS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/STKSTT.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/STKSTTX.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/STKTFR.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/stktfrdetail.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/STPTDS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/styleaddl.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/stylecons.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/STYLEDEF.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/STYLEDETAIL.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/STYLEMASTER.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/STYLEOPERATIONS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/STYLEPROCESSES.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/stylesonlines.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/stylespecs.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/STYLETOT.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/SUBHEADS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/SUPPLIERTABS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/surrender.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/S_SMPREQ.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/taxesandduties.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/TBDT01.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/tcert.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/TEMP.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/TEMPAPPR.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/TERMS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/TMPFORMS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/TOTGRP.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/TOTGRPPO.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/TOTORD.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/TOTPRORD.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/TOTPTY.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/TOTSTY.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/TRANSFER.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/TREEVIEW.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/TYPESOFFABRIC.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/unitconversion.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/UNITS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/users.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/VENDDYE.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/vmiss.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/VOUCHERS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/WEEKS.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/whatsordered.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/whatsorderedpowise.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/YARNCOUNT.sql
mysql -u siddhi -pqaz@123 gems < ../gem2mysql/YEAR.sql
